### ISSUE TITLE
Add fade in-out between the images when navigate into the gallery

### ISSUE THREAD

**Issue by prinkoID** [tobiasroeder/ImageBox#9]
When navigate into the gallery with left and right the next/previous image is fast and create some glitch in some cases (probably only in mobile version)

**Comment by prinkoID** [comment]
It could be better a crossfade, or fade to a color, because now I'm seeing the website during the fade transition

**Comment by tobiasroeder** [comment]
This can be fixed by changing the background color from the ImageBox element in the CSS.
```css
#imagebox {
  background-color: #000;
}
```
